name: Update domains.json files

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  run:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run update

      - run: git commit -a -m "Updated domains.json files"
      - run: git push origin master